global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "photo-service-was"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 10s
    file_sd_configs:
      - files:
          - "/etc/prometheus/targets/was_targets.json"
        refresh_interval: 30s

  - job_name: "photo-service-via-lb"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 10s
    static_configs:
      - targets:
          - "10.0.20.5:8080"
        labels:
          service: "photo-service"
          tier: "internal-lb"
